import * as L from 'leaflet';

// generated by https://geojson-maps.ash.ms/
import * as worldData from './world.geo.json';

import 'leaflet/dist/leaflet.css';
import './app.scss';

const {MAPBOX_ACCESS_TOKEN} = process.env;

const map = L.map('map').setView([50.45, 30.52], 5);

L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
  // tslint:disable-next-line max-line-length
  attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
  maxZoom: 18,
  id: 'mapbox.light',
  accessToken: MAPBOX_ACCESS_TOKEN,
}).addTo(map);

L.geoJSON(worldData as any).addTo(map);

(window as any).L = L;
(window as any).map = map;
