// generated by https://geojson-maps.ash.ms/
import * as worldData from 'data/world.geo.json';

import {Area, Artist} from 'src/types';

function getAreasPlaycounts(artists: Artist[]): {[area: string]: number} {
  const areasPlaycounts = {};

  artists.forEach((artist) => {
    if (!(artist.area in areasPlaycounts)) {
      areasPlaycounts[artist.area] = artist.playcount;
    } else {
      areasPlaycounts[artist.area] += artist.playcount;
    }
  });

  return areasPlaycounts;
}

export function getArtistsAreas(artists: Artist[]): Area[] {
  const areasPlaycounts = getAreasPlaycounts(artists);
  const areas = (worldData as any).features;

  return areas
    .filter((area: Area) => area.properties.name_sort in areasPlaycounts)
    .map((area: Area) => ({
      ...area,
      properties: {
        ...area.properties,
        playcount: areasPlaycounts[area.properties.name_sort],
      },
    }));
}
