import {Config} from 'src/types/config';

const config: Config = {
  dataUrls: {
    artists: 'data/artists.json',
    world: 'data/world.geo.json', // generated by https://geojson-maps.ash.ms/
  },

  controls: {
    toggleAnimationDuration: 400,

    areaInfo: {
      options: {
        position: 'topright',
      },

      username: 'markhovskiy', // last.fm
    },

    areaList: {
      options: {
        position: 'bottomleft',
      },

      itemScaleAnimation: {
        duration: 600,
        delay: 120,
      },
    },

    externalLinkList: {
      options: {
        position: 'bottomright',
      },

      links: {
        github: {
          url: 'https://github.com/music-stats/map',
          text: 'music-stats/map',
        },

        twitter: {
          url: 'https://twitter.com/oleksmarkh',
          text: '@oleksmarkh',
        },
      },
    },
  },

  map: {
    defaultView: {
      center: [50.45, 30.52], // Kyiv
      zoom: 3,
    },

    tileLayer: {
      urlTemplate: 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}',

      options: {
        minZoom: 2,
        maxZoom: 6,
        id: 'mapbox.light',
        attribution: [
          'Map data &copy; <a href="https://openstreetmap.org">OpenStreetMap</a> contributors',
          '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
          'Imagery &copy; <a href="https://mapbox.com">Mapbox</a>',
        ].join(', '),
      },
    },

    area: {
      style: {
        default: {
          weight: 2,
          opacity: 1,
          color: 'white',
          dashArray: '3',
          fillOpacity: 0.6,
        },

        highlight: {
          weight: 3,
          color: '#abc',
          dashArray: '',
          fillOpacity: 0.8,
        },
      },

      fillColorScale: {
        powerExponent: 0.5,
        minRange: 0.1,
        maxRange: 1,
      },
    },
  },
};

export default config;
